[Unit]
After=systemd-udev-settle.service
Wants=systemd-udev-settle.service

[Service]
ExecStartPre=/bin/sh -c 'until [ -e /dev/nvidia0 ]; do sleep 0.1; done'
ExecStart=
ExecStart=/usr/bin/nvidia-persistenced --user nvidia-persistenced --verbose
Restart=on-failure
RestartSec=1
